# Generated by Django 2.0.2 on 2018-06-03 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plastics', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='optimizationjob',
            name='title',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
    ]
