# Generated by Django 2.0.2 on 2018-06-03 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plastics', '0002_optimizationjob_title'),
    ]

    operations = [
        migrations.RenameField(
            model_name='solutioncomponents',
            old_name='solution',
            new_name='solutionset',
        ),
        migrations.AddField(
            model_name='solutionset',
            name='makespan',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
