# Generated by Django 2.0.2 on 2018-06-03 14:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('plastics', '0003_auto_20180603_0942'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='SolutionComponents',
            new_name='SolutionComponent',
        ),
    ]
